quotes = [
  "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
  "Focus on being productive instead of busy.",
  "Productivity comes from commitment to excellence, planning, and focused effort.",
  "Concentrate your thoughts on work. The sun's rays only burn when focused.",
  "Focus does not mean saying yes, it means saying no.",
  "Don't dwell in past or worry about future, focus on living in the present.",
  "Failure isn't fatal, but failure to change might be.",
  "Everything you want is on the other side of fear.",
  "The secret of life is to fall seven times and to get up eight times.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Let improving yourself keep you too busy to criticize others.",
  "Work hard and have fun in what you do to be more successful.",
  "Glory lies not in never falling, but in rising every time we fall.",
  "Do what you believe is great work to be truly satisfied.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "It's not about having enough time, it's about making enough time.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be afraid to give up the good to go for the great.",
  "Discipline is the bridge between goals and accomplishment.",
  "Eliminate inefficient use of information, energy, and time to become more productive.",
  "You don't have to see the whole staircase, just take the first step.",
  "Amateurs wait for inspiration, the rest of us just go to work.",
  "You miss 100% of the shots you don't take.",
  "The harder you work, the greater you'll feel when you achieve it.",
  "There are no shortcuts to any place worth going.",
  "Our only limit to tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Judge days by the seeds you plant, not the harvest you reap.",
  "The successful warrior is the average man, with laser-like focus.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Our greatest weakness is giving up. Success comes from trying one more time.",
  "The way to get started is to quit talking and begin doing.",
  "Either you run the day or the day runs you.",
  "Start where you are. Use what you have. Do what you can.",
  "The difference between ordinary and extraordinary is that little extra.",
  "The question isn't who will let me; it's who will stop me.",
  "Don't count the days, make the days count.",
  "Quality is not an act, it is a habit.",
  "Will you let obstacles stop you? That's the real question.",
  "It always seems impossible until it's done.",
  "The path to success is to take massive, determined action.",
  "If you're going through hell, keep going.",
  "The only way to do great work is to love what you do.",
  "You'll regret the things you didn't do more than the ones you did.",
  "You become what you believe.",
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "Don't waste time living someone else's life.",
  "Success is making a positive difference to the world."
]